import 'dart:async';

import 'package:flutter/material.dart';

class AIExamPage extends StatefulWidget {
  final String jobTitle;
  final String company;

  const AIExamPage({super.key, required this.jobTitle, required this.company});

  @override
  State<AIExamPage> createState() => _AIExamPageState();
}

class _AIExamPageState extends State<AIExamPage> {
  final Color pesoGreen = const Color(0xFF2E7D32);

  // State variables
  int _currentIndex = 0;
  final Map<int, String> _selectedAnswers =
      {}; // Tracks selected option (A, B, C, D)

  // Timer variables
  late Timer _timer;
  int _timeLeftInSeconds = 15 * 60; // 15 Minutes for the 5-question exam

  // --- MOCK DATABASE: AI GENERATED JSON EXAM ---
  // This simulates the exact JSON schema generated by Prompt 1
  final List<Map<String, dynamic>> _mockExamData = [
    {
      "question_id": "q1",
      "difficulty": "Intermediate",
      "skill_tested": "System Architecture",
      "type": "Technical",
      "question_text": "Which architectural pattern is most suited for maintaining highly scalable, decoupled Flutter applications?",
      "options": {
        "A": "MVC (Model-View-Controller)",
        "B": "BLoC / Clean Architecture",
        "C": "Standard StatefulWidget setState()",
        "D": "Singletons for all data management",
      },
      "correct_answer": "B",
    },
    {
      "question_id": "q2",
      "difficulty": "Beginner",
      "skill_tested": "Problem Solving",
      "type": "General Aptitude",
      "question_text": "If a critical server goes down during a peak traffic hour, what is the most appropriate first step in a professional environment?",
      "options": {
        "A": "Immediately rewrite the server code.",
        "B": "Wait for a manager to notice and give instructions.",
        "C": "Communicate the outage to stakeholders and check error logs.",
        "D": "Restart the database without saving states.",
      },
      "correct_answer": "C",
    },
    {
      "question_id": "q3",
      "difficulty": "Intermediate",
      "skill_tested": "API Integration",
      "type": "Technical",
      "question_text": "When making an HTTP GET request that returns a large JSON array, what is the best way to parse this in Dart to avoid UI thread blocking?",
      "options": {
        "A": "Parse it synchronously on the main thread.",
        "B": "Use the compute() function to parse it in a background isolate.",
        "C": "Save the JSON string to SharedPreferences first.",
        "D": "Render the JSON string directly into a Text widget.",
      },
      "correct_answer": "B",
    },
    {
      "question_id": "q4",
      "difficulty": "Advanced",
      "skill_tested": "NoSQL Databases",
      "type": "Technical",
      "question_text": "In a MongoDB database, what is the primary advantage of storing dynamic AI exam results in a single JSON document rather than a relational table?",
      "options": {
        "A": "It enforces strict row schemas.",
        "B": "It requires complex SQL JOIN statements.",
        "C": "It easily accommodates varying question formats and lengths without altering schemas.",
        "D": "It prevents the use of indexing.",
      },
      "correct_answer": "C",
    },
    {
      "question_id": "q5",
      "difficulty": "Intermediate",
      "skill_tested": "Workplace Communication",
      "type": "General Aptitude",
      "question_text": "A client requests a feature that falls completely outside the agreed project scope. How should you respond?",
      "options": {
        "A": "Ignore the request and deliver only what was agreed.",
        "B": "Build the feature immediately to keep them happy.",
        "C": "Acknowledge the idea and propose it as a separate phase or change request.",
        "D": "Tell them the idea is terrible and out of scope.",
      },
      "correct_answer": "C",
    },
  ];

  @override
  void initState() {
    super.initState();
    _startTimer();
  }

  @override
  void dispose() {
    _timer.cancel();
    super.dispose();
  }

  void _startTimer() {
    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      if (_timeLeftInSeconds > 0) {
        setState(() => _timeLeftInSeconds--);
      } else {
        _timer.cancel();
        _submitExam(); // Auto-submit when time is up
      }
    });
  }

  String _formatTime(int totalSeconds) {
    int minutes = totalSeconds ~/ 60;
    int seconds = totalSeconds % 60;
    return '${minutes.toString().padLeft(2, '0')}:${seconds.toString().padLeft(2, '0')}';
  }

  void _submitExam() {
    _timer.cancel();

    // Calculate Score based on mock data
    int correctAnswers = 0;
    for (int i = 0; i < _mockExamData.length; i++) {
      if (_selectedAnswers[i] == _mockExamData[i]['correct_answer']) {
        correctAnswers++;
      }
    }

    double percentage = (correctAnswers / _mockExamData.length) * 100;

    // Return the score to the user_profile.dart page to trigger routing
    Navigator.pop(context, percentage.toInt());
  }

  Future<bool> _onWillPop() async {
    return await showDialog(
          context: context,
          builder: (context) => AlertDialog(
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(15),
            ),
            title: const Text('Quit Assessment?'),
            content: const Text(
              'If you leave now, your progress will be lost and this will count as a failed attempt.',
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.of(context).pop(false),
                child: const Text(
                  'Continue Exam',
                  style: TextStyle(color: Colors.grey),
                ),
              ),
              ElevatedButton(
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.redAccent,
                  foregroundColor: Colors.white,
                ),
                onPressed: () {
                  Navigator.of(context).pop(true);
                  Navigator.of(context).pop(0); // Return 0 score
                },
                child: const Text('Quit Exam'),
              ),
            ],
          ),
        ) ??
        false;
  }

  @override
  Widget build(BuildContext context) {
    final currentQuestion = _mockExamData[_currentIndex];
    final options = currentQuestion['options'] as Map<String, dynamic>;
    final double progress = (_currentIndex + 1) / _mockExamData.length;

    return WillPopScope(
      onWillPop: _onWillPop,
      child: Scaffold(
        backgroundColor: Colors.grey.shade50,
        appBar: _buildDesignerAppBar(),
        body: Column(
          children: [
            // Progress Bar
            LinearProgressIndicator(
              value: progress,
              backgroundColor: Colors.grey.shade200,
              valueColor: AlwaysStoppedAnimation<Color>(pesoGreen),
              minHeight: 6,
            ),

            Expanded(
              child: Center(
                child: ConstrainedBox(
                  constraints: const BoxConstraints(maxWidth: 800),
                  child: Padding(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 40,
                      vertical: 40,
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // AI Context Badges
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Row(
                              children: [
                                _buildBadge(
                                  currentQuestion['type'] == 'Technical'
                                      ? Icons.code
                                      : Icons.psychology,
                                  currentQuestion['type'],
                                  Colors.blue,
                                ),
                                const SizedBox(width: 15),
                                _buildBadge(
                                  Icons.radar,
                                  'Evaluating: ${currentQuestion['skill_tested']}',
                                  Colors.purple,
                                ),
                              ],
                            ),
                            Text(
                              'Question ${_currentIndex + 1} of ${_mockExamData.length}',
                              style: TextStyle(
                                fontSize: 16,
                                fontWeight: FontWeight.bold,
                                color: Colors.grey.shade500,
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 40),

                        // Question Text
                        Text(
                          currentQuestion['question_text'],
                          style: const TextStyle(
                            fontSize: 28,
                            fontWeight: FontWeight.w900,
                            color: Colors.black87,
                            height: 1.4,
                          ),
                        ),
                        const SizedBox(height: 50),

                        // Options List
                        Expanded(
                          child: ListView.builder(
                            itemCount: options.keys.length,
                            itemBuilder: (context, index) {
                              String key = options.keys.elementAt(index);
                              String value = options[key];
                              return _buildInteractiveOptionCard(key, value);
                            },
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ),

            // Footer Navigation
            _buildFooterControls(),
          ],
        ),
      ),
    );
  }

  // --- DESIGNER WIDGETS ---

  AppBar _buildDesignerAppBar() {
    return AppBar(
      backgroundColor: Colors.white,
      elevation: 0,
      toolbarHeight: 90,
      automaticallyImplyLeading: false,
      title: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 20),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Row(
              children: [
                IconButton(
                  icon: const Icon(Icons.close, color: Colors.black54),
                  onPressed: () => _onWillPop(),
                ),
                const SizedBox(width: 15),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Text(
                      'Live AI Assessment',
                      style: TextStyle(
                        color: Colors.grey,
                        fontSize: 13,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      '${widget.jobTitle} @ ${widget.company}',
                      style: const TextStyle(
                        color: Colors.black87,
                        fontSize: 18,
                        fontWeight: FontWeight.w900,
                      ),
                    ),
                  ],
                ),
              ],
            ),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
              decoration: BoxDecoration(
                color: _timeLeftInSeconds < 300
                    ? Colors.red.shade50
                    : Colors.blue.shade50,
                borderRadius: BorderRadius.circular(20),
                border: Border.all(
                  color: _timeLeftInSeconds < 300
                      ? Colors.red.shade200
                      : Colors.blue.shade200,
                ),
              ),
              child: Row(
                children: [
                  Icon(
                    Icons.timer_outlined,
                    size: 18,
                    color: _timeLeftInSeconds < 300
                        ? Colors.red
                        : Colors.blue.shade700,
                  ),
                  const SizedBox(width: 8),
                  Text(
                    _formatTime(_timeLeftInSeconds),
                    style: TextStyle(
                      color: _timeLeftInSeconds < 300
                          ? Colors.red
                          : Colors.blue.shade700,
                      fontWeight: FontWeight.w900,
                      fontSize: 16,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
      bottom: PreferredSize(
        preferredSize: const Size.fromHeight(1),
        child: Container(color: Colors.grey.shade200, height: 1),
      ),
    );
  }

  Widget _buildBadge(IconData icon, String text, MaterialColor color) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: BoxDecoration(
        color: color.shade50,
        borderRadius: BorderRadius.circular(8),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 14, color: color.shade700),
          const SizedBox(width: 6),
          Text(
            text,
            style: TextStyle(
              color: color.shade700,
              fontWeight: FontWeight.bold,
              fontSize: 12,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildInteractiveOptionCard(String key, String text) {
    bool isSelected = _selectedAnswers[_currentIndex] == key;

    return GestureDetector(
      onTap: () => setState(() => _selectedAnswers[_currentIndex] = key),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 250),
        margin: const EdgeInsets.only(bottom: 15),
        padding: const EdgeInsets.all(25),
        decoration: BoxDecoration(
          color: isSelected ? pesoGreen.withValues(alpha: 0.05) : Colors.white,
          borderRadius: BorderRadius.circular(15),
          border: Border.all(
            color: isSelected ? pesoGreen : Colors.grey.shade200,
            width: isSelected ? 2 : 1,
          ),
          boxShadow: isSelected
              ? [
                  BoxShadow(
                    color: pesoGreen.withValues(alpha: 0.1),
                    blurRadius: 15,
                    offset: const Offset(0, 5),
                  ),
                ]
              : [
                  BoxShadow(
                    color: Colors.black.withValues(alpha: 0.02),
                    blurRadius: 10,
                    offset: const Offset(0, 4),
                  ),
                ],
        ),
        child: Row(
          children: [
            AnimatedContainer(
              duration: const Duration(milliseconds: 250),
              width: 35,
              height: 35,
              decoration: BoxDecoration(
                color: isSelected ? pesoGreen : Colors.grey.shade100,
                shape: BoxShape.circle,
                border: Border.all(
                  color: isSelected ? pesoGreen : Colors.grey.shade300,
                ),
              ),
              child: Center(
                child: isSelected
                    ? const Icon(Icons.check, color: Colors.white, size: 20)
                    : Text(
                        key,
                        style: TextStyle(
                          color: Colors.grey.shade600,
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
              ),
            ),
            const SizedBox(width: 20),
            Expanded(
              child: Text(
                text,
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: isSelected ? FontWeight.w700 : FontWeight.w500,
                  color: isSelected ? Colors.black87 : Colors.grey.shade700,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildFooterControls() {
    bool hasAnsweredCurrent = _selectedAnswers.containsKey(_currentIndex);
    bool isLastQuestion = _currentIndex == _mockExamData.length - 1;

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 25),
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 10,
            offset: const Offset(0, -5),
          ),
        ],
      ),
      child: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 800),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              // Previous Button
              _currentIndex > 0
                  ? OutlinedButton.icon(
                      onPressed: () => setState(() => _currentIndex--),
                      icon: const Icon(Icons.arrow_back),
                      label: const Text('Previous'),
                      style: OutlinedButton.styleFrom(
                        foregroundColor: Colors.black87,
                        padding: const EdgeInsets.symmetric(
                          horizontal: 25,
                          vertical: 20,
                        ),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                        side: BorderSide(color: Colors.grey.shade300),
                      ),
                    )
                  : const SizedBox(width: 120), // Placeholder to keep alignment
              // Next / Submit Button
              isLastQuestion
                  ? ElevatedButton.icon(
                      onPressed: hasAnsweredCurrent ? _submitExam : null,
                      icon: const Icon(Icons.send),
                      label: const Text('Submit Assessment'),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: pesoGreen,
                        foregroundColor: Colors.white,
                        elevation: 0,
                        padding: const EdgeInsets.symmetric(
                          horizontal: 35,
                          vertical: 20,
                        ),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                        disabledBackgroundColor: Colors.grey.shade300,
                      ),
                    )
                  : ElevatedButton(
                      onPressed: hasAnsweredCurrent
                          ? () => setState(() => _currentIndex++)
                          : null,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: Colors.black87,
                        foregroundColor: Colors.white,
                        elevation: 0,
                        padding: const EdgeInsets.symmetric(
                          horizontal: 35,
                          vertical: 20,
                        ),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                        disabledBackgroundColor: Colors.grey.shade300,
                      ),
                      child: const Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Text(
                            'Next Question',
                            style: TextStyle(fontWeight: FontWeight.bold),
                          ),
                          SizedBox(width: 10),
                          Icon(Icons.arrow_forward, size: 18),
                        ],
                      ),
                    ),
            ],
          ),
        ),
      ),
    );
  }
}
